FROM python:3.9.6-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

ENV PATH $PATH:/app

ARG DWH_LOGIN
ENV DWH_LOGIN=$DWH_LOGIN
ARG DWH_PASS
ENV DWH_PASS=$DWH_PASS
ARG DWH_IP
ENV DWH_IP=$DWH_IP
ARG DWH_PORT
ENV DWH_PORT=$DWH_PORT
ARG DWH_SERVICE
ENV DWH_SERVICE=$DWH_SERVICE

ARG TABEL_LOGIN
ENV TABEL_LOGIN=$TABEL_LOGIN
ARG TABEL_PASS
ENV TABEL_PASS=$TABEL_PASS
ARG TABEL_IP
ENV TABEL_IP=$TABEL_IP
ARG TABEL_PORT
ENV TABEL_PORT=$TABEL_PORT
ARG TABEL_SERVICE
ENV TABEL_SERVICE=$TABEL_SERVICE

ARG SERVICE_PORT
ENV SERVICE_PORT=$SERVICE_PORT

ARG DEPLOY_SRVR_IP
ENV DEPLOY_SRVR_IP=$DEPLOY_SRVR_IP

ARG DISTRIBUTION_PORT
ENV DISTRIBUTION_PORT=$DISTRIBUTION_PORT

ARG TG_BOT_TOKEN
ENV TG_BOT_TOKEN=$TG_BOT_TOKEN

ARG TG_CHAT_ID
ENV TG_CHAT_ID=$TG_CHAT_ID

ARG TG_TOPIC_ID
ENV TG_TOPIC_ID=$TG_TOPIC_ID

EXPOSE 10503

ENTRYPOINT ["sh", "./start.sh"]
